services:
  jm-news-server:
    build: .
    container_name: jm-news-server
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    environment:
      - NODE_ENV=production
